/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package io.ekwateur.invoice;

import io.ekwateur.invoice.application.InvoiceApplication;

public class App {

  public static void main(String[] args) {
    InvoiceApplication invoiceApplication = new InvoiceApplication();
    invoiceApplication.generate(args);
  }

}
